version: "3"

services:
  app:
    build: .
    ports:
      - 8088:8088
    volumes:
      - .:/async_symfony-service-v2
      - /async_symfony/vendor

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret
